/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.Slovo;
import transfer.KlijentskiZahtev;

/**
 *
 * @author milos
 */
public class KlijentskaForma extends javax.swing.JFrame {

    private String pokusanaSlova="";
    private int preostaliBrojPokusaja=10;
    private int rb;
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        
        komunikacija.Komunikacija.getInstance().start();
        kontroler.Kontroler.getInstance().setKf(this);
        jTextFieldSlovo1.setEnabled(false);
        jTextFieldSlovo2.setEnabled(false);
        jTextFieldSlovo3.setEnabled(false);
        jTextFieldSlovo4.setEnabled(false);
        jTextFieldSlovo5.setEnabled(false);
        jTextFieldPreostaliBrojPokusaja.setEnabled(false);
        jTextFieldKoriscenaSlova.setEnabled(false);
        KlijentskiZahtev kz1=new KlijentskiZahtev(operacije.Operacije.login, null);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz1);
        
        jButton1.setEnabled(false);
    }

    public int getRb() {
        return rb;
    }

    public void setRb(int rb) {
        this.rb = rb;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSlovo1 = new javax.swing.JTextField();
        jTextFieldSlovo2 = new javax.swing.JTextField();
        jTextFieldSlovo3 = new javax.swing.JTextField();
        jTextFieldSlovo4 = new javax.swing.JTextField();
        jTextFieldSlovo5 = new javax.swing.JTextField();
        jTextFieldSlovoPokusaj = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKoriscenaSlova = new javax.swing.JTextField();
        jTextFieldPreostaliBrojPokusaja = new javax.swing.JTextField();
        jLabelRb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Posalji");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Koriscena slova");

        jLabel2.setText("Preostali broj pokusaja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldKoriscenaSlova, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldPreostaliBrojPokusaja, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelRb))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldSlovoPokusaj, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextFieldSlovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldSlovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldSlovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldSlovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(jTextFieldSlovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSlovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSlovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSlovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSlovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSlovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSlovoPokusaj, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldKoriscenaSlova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldPreostaliBrojPokusaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRb)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        jLabelRb.setText(rb+". igrac");
        if( !jTextFieldSlovo1.getText().isEmpty()&&
                !jTextFieldSlovo2.getText().isEmpty()&&
                !jTextFieldSlovo3.getText().isEmpty()&&
                !jTextFieldSlovo4.getText().isEmpty()&&
                !jTextFieldSlovo5.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bravo, pogodio si rec! Tvoj protivnik ce uskoro zavrsiti sa pogadjanjem pa ces saznati ko je pobedio!");
            jButton1.setEnabled(false);
            return;
        }
        Slovo s=new Slovo(Character.toUpperCase(jTextFieldSlovoPokusaj.getText().charAt(0)), new ArrayList<>(),rb);
        if(pokusanaSlova.contains(Character.toUpperCase(jTextFieldSlovoPokusaj.getText().charAt(0))+"")){
            JOptionPane.showMessageDialog(this, "Bilo je to slovo!");
            return;
        }
        pokusanaSlova+=s.getKarakter();
        pokusanaSlova+=", ";
        System.out.println(rb);
        KlijentskiZahtev kz=new KlijentskiZahtev(operacije.Operacije.pogadjanje, (Slovo)s);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        
        
        jTextFieldSlovoPokusaj.setText("");
        preostaliBrojPokusaja--;
        if(preostaliBrojPokusaja<=0){
            JOptionPane.showMessageDialog(this, "Istrosio si sve pokusaje!");
            jButton1.setEnabled(false);
        }
        jTextFieldPreostaliBrojPokusaja.setText(preostaliBrojPokusaja+"");
        jTextFieldKoriscenaSlova.setText(pokusanaSlova);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    public void obavestiIgracaOPocetku() {
        JOptionPane.showMessageDialog(this, "Igra je pocela!");
        jButton1.setEnabled(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelRb;
    private javax.swing.JTextField jTextFieldKoriscenaSlova;
    private javax.swing.JTextField jTextFieldPreostaliBrojPokusaja;
    private javax.swing.JTextField jTextFieldSlovo1;
    private javax.swing.JTextField jTextFieldSlovo2;
    private javax.swing.JTextField jTextFieldSlovo3;
    private javax.swing.JTextField jTextFieldSlovo4;
    private javax.swing.JTextField jTextFieldSlovo5;
    private javax.swing.JTextField jTextFieldSlovoPokusaj;
    // End of variables declaration//GEN-END:variables

    public void pogadjanje(Slovo s) {
        if(s.getPozicije()!=null&&!s.getPozicije().isEmpty()){
            for(int i=0;i<s.getPozicije().size();i++){
                switch (s.getPozicije().get(i)) {
                    case 1:
                        jTextFieldSlovo1.setText(s.getKarakter()+"");
                        break;
                    case 2:
                        jTextFieldSlovo2.setText(s.getKarakter()+"");
                        break;
                    case 3:
                        jTextFieldSlovo3.setText(s.getKarakter()+"");
                        break;
                    case 4:
                        jTextFieldSlovo4.setText(s.getKarakter()+"");
                        break;
                    case 5:
                        jTextFieldSlovo5.setText(s.getKarakter()+"");
                        break;
                        
                    default:
                        throw new AssertionError();
                }
            }
        }
    }

    public void krajIgre(String poruka) {
        JOptionPane.showMessageDialog(this, poruka);
    }

    
}
